[package]
name = "proxy-socks-test"
version = "0.2.0"
edition = "2021"
authors = ["oxychain-dev <linfengfeiye@qq.com>"]
description = "SOCKS proxy test tool"
readme = "README.md"
license = "MIT"
keywords = ["socks", "rust", "test"]
repository = "https://github.com/oxychain-dev/proxy-socks-test"

[dependencies]
libsocks_client = "0.1.4"
tokio = { version = "1.39.3", features = ["full"] }
clap = "4.3.4"
anyhow = "1.0.87"
colored = "2"
rand = "0.8"
reqwest = { version = "0.12.13", default-features = false, features = ["rustls-tls", "socks", "gzip"] }
local-ip-address = "0.6.13"
rusqlite = { version = "0.40.0", features = ["bundled"] }

[profile.release]
strip = true
codegen-units = 1
opt-level = "z"
lto = true
panic = "abort"
